version: '2'

services:
  man:
    build: .
    image: quantumup/reports:1.0.0
    ports:
      - "8080:8080"
      - "9990:9990"
    links:
      - postgres
  postgres:
    image: postgres:latest
    container_name: postgress
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: P@55w0rD
      POSTGRES_DB: reportsDB
    volumes:
      - ./create.sql:/docker-entrypoint-initdb.d/create.sql
