version: '2'


services:
  app:
    build:
      context: .
      # dockerfile: Dockerfile
    # container_name: app
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
